FROM fusionauth/fusionauth-app:latest

ENV POSTGRES_USER ${POSTGRES_USER}
ENV POSTGRES_PASSWORD ${POSTGRES_PASSWORD}

ENV DATABASE_USERNAME ${DATABASE_USERNAME}
ENV DATABASE_PASSWORD ${DATABASE_PASSWORD}

ENV ES_JAVA_OPTS ${ES_JAVA_OPTS}

ENV FUSIONAUTH_APP_MEMORY ${FUSIONAUTH_APP_MEMORY}

CMD /usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.sh run
